site_name: Fast Action Links
repo_url: https://github.com/MegaphoneJon/com.megaphonetech.fastactionlinks
theme: material

pages:
- Home: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
pages:
  - Installation: index.md
  - Quick Start: quick-start.md
  - Configuration: configuration.md
  - Daily Usage: using.md
  - CiviRules integration: civirules-integration.md
